# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageS', '0004_auto_20160104_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_birthday',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_passport',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
