# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StorageS', '0006_auto_20160111_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='auto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StorageS.Auto'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='order_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
